In [5]:
conda install -c conda-forge keras

Solving environment: ...working... done

# All requested packages already installed.


C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>set "KERAS_BACKEND=" 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>python C:\Users\shrut\Anaconda3\etc\keras\load_config.py  1>temp.txt 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>set /p KERAS_BACKEND= 0<temp.txt 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>del temp.txt 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>python -c "import keras"  1>nul 2>&1 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>SET DISTUTILS_USE_SDK=1 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>SET MSSdk=1 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ HandsOn ANN>SET platform= 

C:\Shruthi\Udemy Course_Mine\Deep Learning AZ Ha

ERROR: The system was unable to find the specified registry key or value.
The system cannot find the batch label specified - End


In [1]:
conda install -c conda-forge keras

Solving environment: ...working... done

# All requested packages already installed.


C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set "KERAS_BACKEND=" 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python C:\Users\shrut\Anaconda3\etc\keras\load_config.py  1>temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set /p KERAS_BACKEND= 0<temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>del temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python -c "import keras"  1>nul 2>&1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET DISTUTILS_USE_SDK=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET MSSdk=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET platform= 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_Ha

ERROR: The system was unable to find the specified registry key or value.
The system cannot find the batch label specified - End


In [2]:
conda config --add channels conda-forge



Note: you may need to restart the kernel to use updated packages.


In [4]:
conda install keras

Solving environment: ...working... done

# All requested packages already installed.


C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set "KERAS_BACKEND=" 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python C:\Users\shrut\Anaconda3\etc\keras\load_config.py  1>temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set /p KERAS_BACKEND= 0<temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>del temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python -c "import keras"  1>nul 2>&1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET DISTUTILS_USE_SDK=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET MSSdk=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET platform= 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_Ha

ERROR: The system was unable to find the specified registry key or value.
The system cannot find the batch label specified - End


In [4]:
pip install tensorflow

  Using cached tensorflow-2.1.0-cp37-cp37m-win_amd64.whl (355.8 MB)
  Using cached tensorflow_estimator-2.1.0-py2.py3-none-any.whl (448 kB)
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
  Using cached opt_einsum-3.2.0-py3-none-any.whl (63 kB)
Processing c:\users\shrut\appdata\local\pip\cache\wheels\7c\06\54\bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6\termcolor-1.1.0-cp37-none-any.whl
Processing c:\users\shrut\appdata\local\pip\cache\wheels\8e\28\49\fad4e7f0b9a1227708cbbee4487ac8558a7334849cb81c813d\absl_py-0.9.0-cp37-none-any.whl
Processing c:\users\shrut\appdata\local\pip\cache\wheels\5c\2e\7e\a1d4d4fcebe6c381f378ce7743a3ced3699feb89bcfbdadadd\gast-0.2.2-cp37-none-any.whl
  Using cached google_auth_oauthlib-0.4.1-py2.py3-none-any.whl (18 kB)
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
  Using cached cachetools-4.0.0-py3-none-any.whl (10 kB)
  Using cached rsa-4.0-py2.py3-none-any.whl (38 kB)
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.

In [1]:
pip install keras as keras

  Using cached as-0.1-py3-none-any.whl (2.2 kB)
  Using cached Keras_Preprocessing-1.1.0-py2.py3-none-any.whl (41 kB)
  Using cached Keras_Applications-1.0.8-py3-none-any.whl (50 kB)
Note: you may need to restart the kernel to use updated packages.


In [10]:
conda install -c anacoda keras

Solving environment: ...working... done

# All requested packages already installed.


C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set "KERAS_BACKEND=" 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python C:\Users\shrut\Anaconda3\etc\keras\load_config.py  1>temp.txt 
Note: you may need to restart the kernel to use updated packages.

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set /p KERAS_BACKEND= 0<temp.txt 




ERROR: The system was unable to find the specified registry key or value.
The system cannot find the batch label specified - End


C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>del temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python -c "import keras"  1>nul 2>&1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET DISTUTILS_USE_SDK=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET MSSdk=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET platform= 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>IF /I [AMD64] == [amd64] set "platform=true" 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>IF /I [] == [amd64] set "platform=true" 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStud

In [11]:
conda install -c anacoda keras

Note: you may need to restart the kernel to use updated packages.


ERROR: The system was unable to find the specified registry key or value.
The system cannot find the batch label specified - End



Solving environment: ...working... done

# All requested packages already installed.


C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set "KERAS_BACKEND=" 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python C:\Users\shrut\Anaconda3\etc\keras\load_config.py  1>temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>set /p KERAS_BACKEND= 0<temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>del temp.txt 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>python -c "import keras"  1>nul 2>&1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>if errorlevel 1 (
ver  1>nul  
 set "KERAS_BACKEND=theano"  
 python -c "import keras"  1>nul 2>&1 
) 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET DISTUTILS_USE_SDK=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET MSSdk=1 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN>SET platform= 

C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_H

In [ ]:
conda install -c conda-forge keras

In [42]:
cd C:\Users\shrut\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)

C:\Users\shrut\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)


In [43]:
cd C:\Users\shrut\Anaconda3\lib\site-packages\keras

[WinError 2] The system cannot find the file specified: 'C:\\Users\\shrut\\Anaconda3\\lib\\site-packages\\keras'
C:\Users\shrut\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit)


In [44]:
pip install keras as keras
pip install tensorflow

SyntaxError: invalid syntax (<ipython-input-44-a8278a140ae6>, line 1)

In [45]:
from keras.models import Sequential

In [46]:
cd C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN\Deep_Learning_A_Z\V1 - SDL\Part 1 - ANN\S2 - P1 - ANN


C:\Shruthi\Udemy_Course_Mine\Deep_Learning_AZ_HandsOn_ANN\Deep_Learning_A_Z\V1 - SDL\Part 1 - ANN\S2 - P1 - ANN


Building ANN

In [47]:
## Data PreProcessing

#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#importing datasets
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

#Encoding the dataset
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
labelencoder_x_1 = LabelEncoder()
x[:, 1] = labelencoder_x_1.fit_transform(x[:, 1])

labelencoder_x_2 = LabelEncoder()
x[:, 2] = labelencoder_x_2.fit_transform(x[:, 2])


ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

x = ct.fit_transform(x)
print(x)
x = x[:,1:]
print(x)

#Splitting the dataset into test and train sets
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
print(x_train)
#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)
print(x_train)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 [1.0 0.0 0.0 ... 0 0 93826.63]
 ...
 [0.0 0.0 1.0 ... 1 1 1914.41]
 [0.0 0.0 1.0 ... 1 1 179436.6]
 [0.0 0.0 1.0 ... 1 0 195192.4]]
[[0.0 0.0 619 ... 1 1 101348.88]
 [0.0 0.0 502 ... 1 0 113931.57]
 [0.0 0.0 699 ... 0 0 93826.63]
 ...
 [0.0 1.0 606 ... 1 1 1914.41]
 [0.0 1.0 841 ... 1 1 179436.6]
 [0.0 1.0 726 ... 1 0 195192.4]]
[[1.0 0.0 782 ... 1 0 182960.46]
 [0.0 1.0 741 ... 1 1 13018.96]
 [0.0 0.0 704 ... 0 1 179964.55]
 ...
 [0.0 0.0 652 ... 0 1 110421.31]
 [0.0 1.0 593 ... 1 1 5194.95]
 [0.0 0.0 556 ... 0 1 177670.57]]
[[ 1.72916886 -0.57234647  1.37217993 ...  0.6517324  -1.03771056
   1.43049203]
 [-0.57831252  1.74719344  0.94790427 ...  0.6517324   0.96365985
  -1.52114764]
 [-0.57831252 -0.57234647  0.56502135 ... -1.53437208  0.96365985
   1.37845738]
 ...
 [-0.57831252 -0.57234647  0.02691563 ... -1.53437208  0.96365985
   0.17059123]
 [-0.57831252  1.74719344 -0.58362739 ...  0.6517324   0.96365985
  -1.6

In [48]:
## Building ANN

## Importing the Keras Libraries and packages
import keras
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

## Initializing the ANN
classifier = Sequential()

## Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

## Compiling ANN
classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics= ['accuracy'])

## Fitting the ANN to Training set
classifier.fit(x_train, y_train, batch_size=10,epochs=10)

## Making prediction and evaluating the model


## Predicting the Test set results
y_pred = classifier.predict(x_test)
y_pred = (y_pred > 0.5)

## Making the Confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


Epoch 1/10
8000/8000 [==============================] - 8s 992us/step - loss: 0.4819 - accuracy: 0.7956
Epoch 2/10
8000/8000 [==============================] - 8s 944us/step - loss: 0.4291 - accuracy: 0.7956
Epoch 3/10
8000/8000 [==============================] - 7s 880us/step - loss: 0.4233 - accuracy: 0.8014
Epoch 4/10
8000/8000 [==============================] - 3s 350us/step - loss: 0.4202 - accuracy: 0.8224
Epoch 5/10
8000/8000 [==============================] - 2s 270us/step - loss: 0.4171 - accuracy: 0.8270
Epoch 6/10
8000/8000 [==============================] - 2s 236us/step - loss: 0.4157 - accuracy: 0.8299
Epoch 7/10
8000/8000 [==============================] - 9s 1ms/step - loss: 0.4144 - accuracy: 0.8281: 2s - loss: 0.4111 - accuracy - ETA: 1s - loss: 0.4108 - accuracy: 0.83 - ETA: 1s - loss: 0.4107 - accuracy: 0. - ETA: 1s - los - ETA: 0s - loss: 0.4137 - ac
Epoch 8/10
8000/8000 [==============================] - 11s 1ms/step - loss: 0.4127 - accuracy: 0.8303
Epoch 9/10
80

In [50]:
## Evaluating the ANN (K fold Cross Validation)

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

def build_classifier():
    ## Adding the input layer and the first hidden layer with Dropout
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(p = 0.1))
    
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

    ## Compiling ANN
    classifier.compile(optimizer='adam', loss = 'binary_crossentropy', metrics= ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn=build_classifier, batch_size = 10, nb_epoch = 10)
accuracies = cross_val_score(estimator=classifier, X=x_train, y=y_train, cv = 10, n_jobs=-1)
mean = accuracies.mean()
print(mean)
print(accuracies)
print(classifier)

0.7979999959468842
[0.80874997 0.80374998 0.80124998 0.79000002 0.79250002 0.815
 0.78375    0.79750001 0.79874998 0.78874999]


In [54]:
## Tuning ANN

from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

def build_classifier(optimizer):
    ## Adding the input layer and the first hidden layer with Dropout
    classifier = Sequential()
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))
    classifier.add(Dropout(p = 0.1))
    
    classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

    ## Compiling ANN
    classifier.compile(optimizer=optimizer, loss = 'binary_crossentropy', metrics= ['accuracy'])
    return classifier

classifier = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size' : [25, 32], 'nb_epoch' : [10, 25], 'optimizer' : ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator=classifier, param_grid = parameters, scoring='accuracy', cv=10)
grid_search = grid_search.fit(x_train, y_train)
best_parameters = grid_search.best_params_
best_accuray = grid_search.best_score_


print(best_parameters, best_accuray)



C:\Anaconda\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dropout` call to the Keras 2 API: `Dropout(rate=0.1)`
  del sys.path[0]


Epoch 1/1
7200/7200 [==============================] - 0s 52us/step - loss: 0.5574 - accuracy: 0.7925
Epoch 1/1
7200/7200 [==============================] - 0s 54us/step - loss: 0.5619 - accuracy: 0.7961
Epoch 1/1
7200/7200 [==============================] - 0s 57us/step - loss: 0.5757 - accuracy: 0.7944
Epoch 1/1
7200/7200 [==============================] - 0s 60us/step - loss: 0.5921 - accuracy: 0.7944
Epoch 1/1
7200/7200 [==============================] - 0s 52us/step - loss: 0.5612 - accuracy: 0.7935
Epoch 1/1
7200/7200 [==============================] - 0s 53us/step - loss: 0.6033 - accuracy: 0.7921
Epoch 1/1
7200/7200 [==============================] - 0s 56us/step - loss: 0.5421 - accuracy: 0.7969
Epoch 1/1
7200/7200 [==============================] - 0s 54us/step - loss: 0.5525 - accuracy: 0.7947
Epoch 1/1
7200/7200 [==============================] - 0s 52us/step - loss: 0.5632 - accuracy: 0.7949
Epoch 1/1
7200/7200 [==============================] - 0s 58us/step - loss: 0.5770

8000/8000 [==============================] - 0s 52us/step - loss: 0.5527 - accuracy: 0.7952
{'batch_size': 25, 'nb_epoch': 10, 'optimizer': 'adam'} 0.795625
